version: '3'
services:
  bot:
    container_name: processing-support-bot
    build: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    network_mode: host
