version: '3'
services:
  bot:
    container_name: AloqaBankATMSupportBot
    build: .
    restart: always
    environment:
      - TOKEN=6256030003:AAHt1Ui_MZFEkz7wngxLabxoeihRx4Fn-lg
      - DB_HOST=68.183.75.13
      - DB_USER=test
      - DB_PASSWORD=@bvMT2j0Q05q
      - DB_NAME=SupportBot
    network_mode: host